launchpad-services/appdev-documentation.yaml
@gastaldi mind taking a look and merging?
=> 2017.08.14 docs prod deploy

launchpad-services/appdev-documentation.yaml
This PR has been created per documentation issue [#496](https://github.com/openshiftio/appdev-documentation/issues/496)
=> 2017-08-14_2 republish contrib guide

launchpad-services/appdev-documentation.yaml
@gastaldi The new release is ready, please merge:)
=> 2017-08-28 Docs prod release

launchpad-services/appdev-documentation.yaml
=>  2017.09.08 docs prod release

launchpad-services/appdev-documentation.yaml
=> 2017.09.26 docs push to prod

launchpad-services/appdev-documentation.yaml
@gastaldi mind merging when you have a chance?
=>  2017.11.22 prod push

launchpad-services/appdev-documentation.yaml
@gastaldi mind merging when you have a chance?
=> 2017.11.30 prod push

launchpad-services/appdev-documentation.yaml
@gastaldi mind merging when you have a chance?
=>  2017.12.01 prod push

launchpad-services/launcher-documentation.yaml
@gastaldi mind merging when you have a chance?
=> 2018.02.02 docs push

launchpad-services/backend.yaml, launchpad-services/frontend.yaml
Merge only after the booster-catalog tag is created and updated in production
=> Update production to latest booster catalog changes

launchpad-services/launcher-documentation.yaml
@gastaldi please merge this when you have a chance
=> 2018.02.20 docs push

launchpad-services/launcher-documentation.yaml
@gastaldi mind merging this when you have a chance?
=> Upstream docs prod push on 2018.03.08

launchpad-services/backend.yaml
Ignoring error being sent to sentry
=> update(backend): Ignoring useless error

launchpad-services/backend.yaml
- Using new Booster catalog structure
- Using new fabric8-jenkinsfile-library structure
=> update(backend): API changes

launchpad-services/backend.yaml
Updates FMP to 3.5.38 and kubernetes-api to 3.0.11
=> update(backend): Update FMP and K8S API version

launchpad-services/backend.yaml
Reverts openshiftio/saas-launchpad#53
=> Revert "update(backend): Update FMP and K8S API version"

launchpad-services/launcher-documentation.yaml
@gastaldi can you merge this when you have a chance?
=> 2018.03.29 upstream docs push

launchpad-services/backend.yaml
As an attempt to figure out if that impacts Websocket calls
=> Changing prod to 1 replica

launchpad-services/backend.yaml
To test the haproxy.router.openshift.io/balance=source annotation in the route
=> Increased replica count for prod-preview

launchpad-services/backend.yaml
Reverts openshiftio/saas-launchpad#92
=> Revert "Update backend.yaml"

launchpad-services/launcher-documentation.yaml
Please deploy after verifying that the RHEL based documentation is working
properly in prod-preview
=> Deploy RHEL based documentation to prod

launchpad-services/frontend.yaml
Reverts openshiftio/saas-launchpad#126
=> Revert "Update frontend.yaml"

launchpad-services/launcher-documentation.yaml
@gastaldi let me know what you think
=>  2018.06.21 upstream prod push

launchpad-services/launcher-documentation.yaml
@gastaldi Please merge if this looks ok to you:) thank you
=> 2018-08-15 upstream docs prod push

launchpad-services/launcher-documentation.yaml
@gastaldi Please flee free to merge this when you have a chance. Thank you:)
=> bumped SHA for the 2018-08-28 upstream docs release

launchpad-services/launcher-documentation.yaml
@gastaldi Please feel free to merge this when you have a chance:) Thank you:)
=> 2018-09-13_docs_prod_push

launchpad-services/frontend.yaml
=> new release

launchpad-services/launcher-documentation.yaml
@tradej @inoxx03 Please review and merge.
=> Launcher docs release 2019-06-25
